
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {

    tutorialSidebar: [
        {
            type: 'autogenerated',
            dirName: 'ClasesAbstractas',
        },
        {
            type: 'autogenerated',
            dirName: 'Interfaces',
        },
    ],
};

export default sidebars;
